-- Employee cards and managed manual choices. Existing manual reports remain
-- immutable; no operational tables, permissions, or v1 RPCs are changed.
begin;

create or replace function greenloop_private.manual_damage_normalized(p_label text)
returns text language sql immutable strict
set search_path=pg_catalog,public as $normalize$
 select lower(btrim(regexp_replace(p_label,'[[:space:]]+',' ','g')));
$normalize$;
revoke all on function greenloop_private.manual_damage_normalized(text) from public,anon,authenticated;

create table if not exists public.manual_damage_options (
 id uuid primary key default gen_random_uuid(),
 kind text not null check(kind in ('employee','model','part','reason')),
 label text not null,
 normalized_label text generated always as (greenloop_private.manual_damage_normalized(label)) stored,
 sort_order bigint generated by default as identity (start with 1000),
 is_active boolean not null default true,
 created_at timestamptz not null default now(),
 created_by uuid,
 archived_at timestamptz,
 archived_by uuid,
 restored_at timestamptz,
 restored_by uuid,
 check(char_length(label) between 1 and case kind when 'employee' then 120 when 'model' then 160 when 'part' then 120 else 2000 end),
 check(char_length(normalized_label)>0),
 unique(kind,normalized_label)
);
comment on table public.manual_damage_options is
 'Manual damage employee/choice catalog. Delete archives a choice; adding the same normalized label restores its original ID. No operational/user foreign keys.';
alter table public.manual_damage_options enable row level security;
revoke all on public.manual_damage_options from public,anon,authenticated;
revoke all on sequence public.manual_damage_options_sort_order_seq from public,anon,authenticated;

-- ON CONFLICT never changes existing activation or audit fields on replay.
insert into public.manual_damage_options(kind,label,sort_order)
select 'employee',label,ordinality from unnest(array[
 'ZULFIQAR','SHAMS','IKRAM','WAJAHAT','AKRAM','SADAM','SHAHID','LU','DUKE','DU JIAN','CHEN','QASEEM','AMIR SAIF',
 'ABUBEKER','WAHID','KHURAM','EYOB MESFIN','EHTASHAM','FEDILU','HUSSEN','WONDAMAGEGAN','GETACHEW','YENENEW','OSAMA','AMIR TUHAR','AMANUEL'
]) with ordinality as names(label,ordinality)
on conflict(kind,normalized_label) do nothing;

-- Only values actually entered in manual reports become initial choices.
-- Parts intentionally start empty: an old damage description is not a part.
insert into public.manual_damage_options(kind,label)
select kind,label from (
 select distinct on (kind,greenloop_private.manual_damage_normalized(label)) kind,
  btrim(regexp_replace(label,'[[:space:]]+',' ','g')) as label
 from (
  select 'model'::text as kind,model as label,created_at,id from public.manual_damage_reports
  union all select 'reason',reason,created_at,id from public.manual_damage_reports
 ) source
 order by kind,greenloop_private.manual_damage_normalized(label),created_at,id
) choices
on conflict(kind,normalized_label) do nothing;

alter table public.manual_damage_reports add column if not exists employee_id uuid;
alter table public.manual_damage_reports add column if not exists part_name text
 check(part_name is null or char_length(part_name) between 1 and 120);
comment on column public.manual_damage_reports.employee_id is
 'Stable manual catalog employee identity for v2 reports. Legacy reports retain NULL and match cards by normalized damaged_by snapshot.';
comment on column public.manual_damage_reports.part_name is
 'Selected part snapshot for v2 reports. NULL means no part was recorded; legacy damage text is never inferred as a part.';
create index if not exists manual_damage_reports_employee_recent
 on public.manual_damage_reports(employee_id,occurred_at desc,id desc);
create index if not exists manual_damage_reports_legacy_employee_recent
 on public.manual_damage_reports(greenloop_private.manual_damage_normalized(damaged_by),occurred_at desc,id desc)
 where employee_id is null;

create or replace function public.get_manual_damage_options_v1()
returns jsonb language plpgsql stable security definer
set search_path=pg_catalog,public as $options$
declare v_result jsonb;
begin
 if not greenloop_private.manual_damage_access() then
  raise exception 'Lab Live Board view permission is required to view manual damage.' using errcode='42501';
 end if;
 select jsonb_build_object(
  'employees',coalesce(jsonb_agg(jsonb_build_object('id',id,'label',label) order by sort_order,id) filter(where kind='employee'),'[]'::jsonb),
  'models',coalesce(jsonb_agg(jsonb_build_object('id',id,'label',label) order by sort_order,id) filter(where kind='model'),'[]'::jsonb),
  'parts',coalesce(jsonb_agg(jsonb_build_object('id',id,'label',label) order by sort_order,id) filter(where kind='part'),'[]'::jsonb),
  'reasons',coalesce(jsonb_agg(jsonb_build_object('id',id,'label',label) order by sort_order,id) filter(where kind='reason'),'[]'::jsonb)
 ) into v_result from public.manual_damage_options where is_active;
 return v_result;
end;
$options$;

create or replace function public.add_manual_damage_option_v1(p_kind text,p_label text)
returns jsonb language plpgsql security definer
set search_path=pg_catalog,public as $add$
declare
 v_label text:=btrim(regexp_replace(coalesce(p_label,''),'[[:space:]]+',' ','g'));
 v_max integer;
 v_option public.manual_damage_options%rowtype;
begin
 if not greenloop_private.manual_damage_access(true) then
  raise exception 'Lab Live Board edit permission is required to manage manual damage choices.' using errcode='42501';
 end if;
 v_max:=case p_kind when 'employee' then 120 when 'model' then 160 when 'part' then 120 when 'reason' then 2000 end;
 if v_max is null then raise exception 'Choose a valid manual damage option kind.' using errcode='22023'; end if;
 if char_length(v_label) not between 1 and v_max then
  raise exception 'A label is required and must be at most % characters.',v_max using errcode='22023';
 end if;
 insert into public.manual_damage_options(kind,label,created_by)
 values(p_kind,v_label,auth.uid())
 on conflict(kind,normalized_label) do update
 set is_active=true,
  restored_at=case when not manual_damage_options.is_active then now() else manual_damage_options.restored_at end,
  restored_by=case when not manual_damage_options.is_active then auth.uid() else manual_damage_options.restored_by end
 returning * into v_option;
 return jsonb_build_object('id',v_option.id,'label',v_option.label);
end;
$add$;

create or replace function public.archive_manual_damage_option_v1(p_kind text,p_id uuid)
returns jsonb language plpgsql security definer
set search_path=pg_catalog,public as $archive$
declare v_id uuid;
begin
 if not greenloop_private.manual_damage_access(true) then
  raise exception 'Lab Live Board edit permission is required to manage manual damage choices.' using errcode='42501';
 end if;
 if p_kind is null or p_kind not in ('employee','model','part','reason') then
  raise exception 'Choose a valid manual damage option kind.' using errcode='22023';
 end if;
 update public.manual_damage_options set is_active=false,
  archived_at=case when is_active then now() else archived_at end,
  archived_by=case when is_active then auth.uid() else archived_by end
 where id=p_id and kind=p_kind returning id into v_id;
 if not found then raise exception 'This manual damage choice does not exist.' using errcode='22023'; end if;
 return jsonb_build_object('id',v_id);
end;
$archive$;

create or replace function public.create_manual_damage_report_v2(
 p_request_id uuid,p_employee_id uuid,p_model_id uuid,p_part_id uuid,p_reason_id uuid,
 p_identifier text,p_occurred_at timestamptz
)
returns jsonb language plpgsql security definer
set search_path=pg_catalog,public as $create$
declare
 v_actor uuid:=auth.uid();
 v_identifier text:=nullif(btrim(coalesce(p_identifier,''),E' \t\n\r\f'),'');
 v_reported_by text;
 v_employee public.manual_damage_options%rowtype;
 v_model public.manual_damage_options%rowtype;
 v_part public.manual_damage_options%rowtype;
 v_reason public.manual_damage_options%rowtype;
 v_row public.manual_damage_reports%rowtype;
 v_existing boolean;
begin
 if not greenloop_private.manual_damage_access(true) then
  raise exception 'Lab Live Board edit permission is required to record manual damage.' using errcode='42501';
 end if;
 if p_request_id is null then raise exception 'A request ID is required.' using errcode='22023'; end if;
 if char_length(v_identifier)>120 then raise exception 'Identifier must be at most 120 characters.' using errcode='22023'; end if;
 if p_occurred_at is null or not isfinite(p_occurred_at) or p_occurred_at>now()+interval '5 minutes' then
  raise exception 'Enter a valid incident date and time, no more than five minutes in the future.' using errcode='22023';
 end if;

 -- Serialize the same actor/request before examining activation. A retry of a
 -- committed request remains valid after any selected choice was archived.
 perform pg_advisory_xact_lock(hashtextextended(v_actor::text||':'||p_request_id::text,0));
 select * into v_row from public.manual_damage_reports where reported_by_user_id=v_actor and request_id=p_request_id;
 v_existing:=found;
 -- Lock choices in a fixed order so archive cannot race a new report commit.
 perform 1 from public.manual_damage_options
 where id in (p_employee_id,p_model_id,p_part_id,p_reason_id) order by id for share;
 select * into v_employee from public.manual_damage_options where id=p_employee_id and kind='employee';
 select * into v_model from public.manual_damage_options where id=p_model_id and kind='model';
 select * into v_part from public.manual_damage_options where id=p_part_id and kind='part';
 select * into v_reason from public.manual_damage_options where id=p_reason_id and kind='reason';
 if v_employee.id is null or v_model.id is null or v_part.id is null or v_reason.id is null then
  raise exception 'Select an employee, model, part name, and reason from the available choices.' using errcode='22023';
 end if;
 if v_existing then
  if row(v_row.employee_id,v_row.model,v_row.part_name,v_row.reason,v_row.identifier,v_row.occurred_at)
    is distinct from row(v_employee.id,v_model.label,v_part.label,v_reason.label,v_identifier,p_occurred_at) then
   raise exception 'This request ID was already used for different manual damage details.' using errcode='22023';
  end if;
  return to_jsonb(v_row)-'request_id'-'reported_by_user_id';
 end if;
 if not(v_employee.is_active and v_model.is_active and v_part.is_active and v_reason.is_active) then
  raise exception 'A selected employee or choice was deleted. Refresh the choices before saving.' using errcode='22023';
 end if;
 select coalesce(nullif(btrim(u.full_name),''),nullif(btrim(u.login_username),''),'Staff')
 into v_reported_by from public.user_profiles u where u.id=v_actor;
 -- The old required damage field stores the selected part label for v2 rows.
 -- Actual part display always uses the separate, explicit part_name snapshot.
 insert into public.manual_damage_reports(request_id,reported_by_user_id,reported_by,
  damaged_by,employee_id,model,identifier,damage,part_name,reason,occurred_at)
 values(p_request_id,v_actor,coalesce(v_reported_by,'Staff'),v_employee.label,v_employee.id,
  v_model.label,v_identifier,v_part.label,v_part.label,v_reason.label,p_occurred_at)
 on conflict(reported_by_user_id,request_id) do nothing returning * into v_row;
 if not found then
  select * into strict v_row from public.manual_damage_reports where reported_by_user_id=v_actor and request_id=p_request_id;
  if row(v_row.employee_id,v_row.model,v_row.part_name,v_row.reason,v_row.identifier,v_row.occurred_at)
    is distinct from row(v_employee.id,v_model.label,v_part.label,v_reason.label,v_identifier,p_occurred_at) then
   raise exception 'This request ID was already used for different manual damage details.' using errcode='22023';
  end if;
 end if;
 return to_jsonb(v_row)-'request_id'-'reported_by_user_id';
end;
$create$;

create or replace function public.get_manual_damage_employee_rows_v1(
 p_employee_id uuid,p_offset integer default 0,p_limit integer default 6
)
returns jsonb language plpgsql stable security definer
set search_path=pg_catalog,public as $rows$
declare
 v_offset integer:=greatest(0,least(coalesce(p_offset,0),1000000));
 v_limit integer:=greatest(1,least(coalesce(p_limit,6),100));
 v_normalized text;
 v_count bigint;
 v_rows jsonb;
begin
 if not greenloop_private.manual_damage_access() then
  raise exception 'Lab Live Board view permission is required to view manual damage.' using errcode='42501';
 end if;
 select normalized_label into v_normalized from public.manual_damage_options where id=p_employee_id and kind='employee' and is_active;
 if not found then raise exception 'This employee does not exist.' using errcode='22023'; end if;
 select count(*) into v_count from public.manual_damage_reports
 where employee_id=p_employee_id or (employee_id is null and greenloop_private.manual_damage_normalized(damaged_by)=v_normalized);
 select coalesce(jsonb_agg(to_jsonb(r) order by r.occurred_at desc,r.id desc),'[]'::jsonb) into v_rows
 from (select id,occurred_at,model,part_name,reason,identifier,reported_by,created_at
  from public.manual_damage_reports
  where employee_id=p_employee_id or (employee_id is null and greenloop_private.manual_damage_normalized(damaged_by)=v_normalized)
  order by occurred_at desc,id desc offset v_offset limit v_limit) r;
 return jsonb_build_object('employee_id',p_employee_id,'total_damage',v_count,'rows',v_rows,
  'has_more',v_offset::bigint+v_limit<v_count);
end;
$rows$;

create or replace function public.get_manual_damage_cards_v1(
 p_offset integer default 0,p_limit integer default 4,p_row_limit integer default 6
)
returns jsonb language plpgsql stable security definer
set search_path=pg_catalog,public as $cards$
declare
 v_offset integer:=greatest(0,least(coalesce(p_offset,0),1000000));
 v_limit integer:=greatest(1,least(coalesce(p_limit,4),100));
 v_row_limit integer:=greatest(1,least(coalesce(p_row_limit,6),100));
 v_today date:=(now() at time zone 'Asia/Dubai')::date;
 v_month timestamp:=date_trunc('month',now() at time zone 'Asia/Dubai');
 v_employee_count bigint; v_today_count bigint; v_month_count bigint; v_total_count bigint;
 v_employees jsonb;
begin
 if not greenloop_private.manual_damage_access() then
  raise exception 'Lab Live Board view permission is required to view manual damage.' using errcode='42501';
 end if;
 select count(*) into v_employee_count from public.manual_damage_options where kind='employee' and is_active;
 select count(*),
  count(*) filter(where occurred_at>=v_today::timestamp at time zone 'Asia/Dubai'
   and occurred_at<(v_today+1)::timestamp at time zone 'Asia/Dubai'),
  count(*) filter(where occurred_at>=v_month at time zone 'Asia/Dubai'
   and occurred_at<(v_month+interval '1 month') at time zone 'Asia/Dubai')
 into v_total_count,v_today_count,v_month_count from public.manual_damage_reports;
 select coalesce(jsonb_agg(jsonb_build_object('id',e.id,'name',e.label,
  'total_damage',h.data->'total_damage','rows',h.data->'rows','has_more',h.data->'has_more') order by e.sort_order,e.id),'[]'::jsonb)
 into v_employees from (select id,label,sort_order from public.manual_damage_options where kind='employee' and is_active
  order by sort_order,id offset v_offset limit v_limit) e
 cross join lateral (select public.get_manual_damage_employee_rows_v1(e.id,0,v_row_limit) as data) h;
 return jsonb_build_object('employee_count',v_employee_count,'today_count',v_today_count,'month_count',v_month_count,
  'total_count',v_total_count,'employees',v_employees,'has_more',v_offset::bigint+v_limit<v_employee_count);
end;
$cards$;

revoke all on function public.get_manual_damage_options_v1() from public,anon;
revoke all on function public.add_manual_damage_option_v1(text,text) from public,anon;
revoke all on function public.archive_manual_damage_option_v1(text,uuid) from public,anon;
revoke all on function public.create_manual_damage_report_v2(uuid,uuid,uuid,uuid,uuid,text,timestamptz) from public,anon;
revoke all on function public.get_manual_damage_employee_rows_v1(uuid,integer,integer) from public,anon;
revoke all on function public.get_manual_damage_cards_v1(integer,integer,integer) from public,anon;
grant execute on function public.get_manual_damage_options_v1() to authenticated;
grant execute on function public.add_manual_damage_option_v1(text,text) to authenticated;
grant execute on function public.archive_manual_damage_option_v1(text,uuid) to authenticated;
grant execute on function public.create_manual_damage_report_v2(uuid,uuid,uuid,uuid,uuid,text,timestamptz) to authenticated;
grant execute on function public.get_manual_damage_employee_rows_v1(uuid,integer,integer) to authenticated;
grant execute on function public.get_manual_damage_cards_v1(integer,integer,integer) to authenticated;

create table if not exists greenloop_private.damage_employee_cards_installation(
 function_identity text primary key,definition_hash text not null);
revoke all on greenloop_private.damage_employee_cards_installation from public,anon,authenticated;
insert into greenloop_private.damage_employee_cards_installation
select p.oid::regprocedure::text,md5(pg_get_functiondef(p.oid)) from pg_proc p
where p.oid in ('greenloop_private.manual_damage_normalized(text)'::regprocedure,
 'public.get_manual_damage_options_v1()'::regprocedure,
 'public.add_manual_damage_option_v1(text,text)'::regprocedure,
 'public.archive_manual_damage_option_v1(text,uuid)'::regprocedure,
 'public.create_manual_damage_report_v2(uuid,uuid,uuid,uuid,uuid,text,timestamptz)'::regprocedure,
 'public.get_manual_damage_employee_rows_v1(uuid,integer,integer)'::regprocedure,
 'public.get_manual_damage_cards_v1(integer,integer,integer)'::regprocedure)
on conflict(function_identity) do update set definition_hash=excluded.definition_hash;

create or replace function public.get_damage_employee_cards_version()
returns text language sql stable security definer set search_path=pg_catalog,public as $version$
 select case when public.get_manual_damage_report_version()='20261003-manual-damage-1'
 and (select count(*)=7 and bool_and(to_regprocedure(i.function_identity) is not null
  and md5(pg_get_functiondef(to_regprocedure(i.function_identity)))=i.definition_hash
  and not has_function_privilege('anon',to_regprocedure(i.function_identity),'EXECUTE')
  and has_function_privilege('authenticated',to_regprocedure(i.function_identity),'EXECUTE')=(i.function_identity not like 'greenloop_private.%'))
  from greenloop_private.damage_employee_cards_installation i)
 and exists(select 1 from pg_class where oid='public.manual_damage_options'::regclass and relrowsecurity)
 and not has_table_privilege('authenticated','public.manual_damage_options','SELECT,INSERT,UPDATE,DELETE,TRUNCATE')
 and not has_table_privilege('anon','public.manual_damage_options','SELECT,INSERT,UPDATE,DELETE,TRUNCATE')
 and not has_table_privilege('authenticated','greenloop_private.damage_employee_cards_installation','SELECT,INSERT,UPDATE,DELETE,TRUNCATE')
 and not has_table_privilege('anon','greenloop_private.damage_employee_cards_installation','SELECT,INSERT,UPDATE,DELETE,TRUNCATE')
 and exists(select 1 from pg_attribute where attrelid='public.manual_damage_reports'::regclass and attname='employee_id' and atttypid='uuid'::regtype and not attnotnull and not attisdropped)
 and exists(select 1 from pg_attribute where attrelid='public.manual_damage_reports'::regclass and attname='part_name' and atttypid='text'::regtype and not attnotnull and not attisdropped)
 then '20261003-damage-cards-1' end;
$version$;
revoke all on function public.get_damage_employee_cards_version() from public;
grant execute on function public.get_damage_employee_cards_version() to anon,authenticated;
notify pgrst,'reload schema';
commit;
select public.get_damage_employee_cards_version() as installed_damage_employee_cards_version;
