-- Greenloop IMEI journey: additive read-only report. No data or workflow is changed.
begin;
create schema if not exists greenloop_private;
create or replace function greenloop_private.imei_journey_details(p_values jsonb)
returns jsonb language sql immutable set search_path=pg_catalog as $details$
select coalesce(jsonb_agg(jsonb_build_object('label',key,'value',value) order by key),'[]'::jsonb)
from jsonb_each(p_values) where value<>'null'::jsonb and value<>'""'::jsonb;
$details$;
revoke all on function greenloop_private.imei_journey_details(jsonb) from public,anon,authenticated;

create or replace function public.search_imei_journey_v1(p_imei text)
returns jsonb language plpgsql stable security definer set search_path=pg_catalog,public as $journey$
declare v_query text:=nullif(btrim(p_imei),''); v_device public.devices%rowtype; v_names boolean; v_rows jsonb; v_summary jsonb; v_result jsonb; v_matches integer;
begin
 if auth.uid() is null or not coalesce(public.is_active_staff(),false) or not coalesce(
 (select p.access_level in ('view','edit') from public.user_page_permissions p where p.user_id=auth.uid() and p.page_key='imei_search'),
 public.has_role(array['owner','super_admin']::public.app_role_key[]),false) then
 raise exception 'IMEI Search permission is required.' using errcode='42501'; end if;
 if v_query is null or length(v_query)>120 then raise exception 'Enter an IMEI, device number or serial number.' using errcode='22023'; end if;
 select count(*) into v_matches from public.devices d where d.deleted_at is null and
 (d.imei_1=v_query or d.imei_2=v_query or lower(d.device_number)=lower(v_query) or lower(d.serial_number)=lower(v_query));
 if v_matches>1 then raise exception 'This identifier matches more than one device. Search with its exact IMEI instead.' using errcode='22023'; end if;
 select d.* into v_device from public.devices d where d.deleted_at is null and
 (d.imei_1=v_query or d.imei_2=v_query or lower(d.device_number)=lower(v_query) or lower(d.serial_number)=lower(v_query))
 order by case when d.imei_1=v_query then 0 when d.imei_2=v_query then 1 else 2 end,d.id limit 1;
 if v_device.id is null then return jsonb_build_object('found',false); end if;
 v_names:=coalesce(public.get_my_partner_name_access(),false);
 with device_jobs as (select * from public.jobs where device_id=v_device.id and deleted_at is null),
 structured as (
select b.received_at occurred_at, 10 sort_order, null::uuid job_id, jsonb_build_object('id', 'receipt:'||b.id, 'occurred_at', b.received_at, 'stage', 'stock_received', 'title', 'Stock received', 'actor', (select nullif(btrim(p.full_name),'') from public.user_profiles p where p.id=b.created_by), 'job_number', null, 'status', 'received', 'details', greenloop_private.imei_journey_details(jsonb_build_object('Receipt', b.batch_number, 'Invoice', b.invoice_number, 'Supplier code', s.supplier_code, 'Supplier name', case when v_names then s.company_name else null end, 'Quantity received', b.planned_quantity, 'Stock channel', c.channel_name)), 'parts', '[]'::jsonb, 'cost', null, 'duration_seconds', null, 'duration_label', null, 'source', 'stock_received') data
from public.receiving_batches b join (select distinct receiving_batch_id from device_jobs where receiving_batch_id is not null) linked on linked.receiving_batch_id=b.id left join public.suppliers s on s.id=b.supplier_id left join public.stock_channels c on c.id=b.stock_channel_id
union all
select j.received_at occurred_at, 10 sort_order, j.id job_id, jsonb_build_object('id', 'individual-receipt:'||j.id, 'occurred_at', j.received_at, 'stage', 'stock_received', 'title', 'Device received (individual job)', 'actor', (select nullif(btrim(p.full_name),'') from public.user_profiles p where p.id=j.received_by), 'job_number', j.job_number, 'status', 'received', 'details', greenloop_private.imei_journey_details(jsonb_build_object('Supplier code', s.supplier_code, 'Supplier name', case when v_names then s.company_name else null end, 'Receipt type', 'Individual job; no stock batch linked', 'Stock channel', j.receiving_source)), 'parts', '[]'::jsonb, 'cost', null, 'duration_seconds', null, 'duration_label', null, 'source', 'stock_received') data
from device_jobs j left join public.suppliers s on s.id=j.supplier_id where j.receiving_batch_id is null
union all
select j.created_at occurred_at, 20 sort_order, j.id job_id, jsonb_build_object('id', 'entry:'||j.id, 'occurred_at', j.created_at, 'stage', 'imei_entry', 'title', case when j.created_at=(select min(created_at) from device_jobs) then 'IMEI entered' else 'IMEI received for another job' end, 'actor', (select nullif(btrim(p.full_name),'') from public.user_profiles p where p.id=coalesce(j.created_by,j.received_by)), 'job_number', j.job_number, 'status', 'received', 'details', greenloop_private.imei_journey_details(jsonb_build_object('Supplier code', (select s.supplier_code from public.suppliers s where s.id=j.supplier_id), 'Supplier name', case when v_names then (select s.company_name from public.suppliers s where s.id=j.supplier_id) else null end, 'Customer code', (select c.customer_code from public.customers c where c.id=j.customer_id), 'Customer name', case when v_names then (select c.company_name from public.customers c where c.id=j.customer_id) else null end, 'Job type', replace(j.job_type::text,'_',' '), 'Supplier grade', j.supplier_grade, 'Cost basis', 'Recorded purchase cost for this job')), 'parts', '[]'::jsonb, 'cost', j.purchase_cost, 'duration_seconds', null, 'duration_label', null, 'source', 'imei_entry') data
from device_jobs j
union all
select r.inspected_at occurred_at, 50 sort_order, j.id job_id, jsonb_build_object('id', 'initial-qc:'||r.id, 'occurred_at', r.inspected_at, 'stage', 'initial_qc', 'title', 'Initial QC inspection', 'actor', (select nullif(btrim(p.full_name),'') from public.user_profiles p where p.id=r.inspected_by), 'job_number', j.job_number, 'status', null, 'details', greenloop_private.imei_journey_details(jsonb_build_object('Condition', r.overall_condition, 'Cosmetic condition', r.cosmetic_condition, 'Work required', case when r.work_required then 'Yes' else 'No' end, 'Findings', (select string_agg(concat_ws(' — ',f.check_item,f.action_required,replace(f.department::text,'_',' ')), '; ' order by f.created_at,f.id) from public.initial_qc_findings f where f.inspection_id=r.id and f.issue_found), 'Notes', case when v_names then r.notes else null end)), 'parts', '[]'::jsonb, 'cost', null, 'duration_seconds', null, 'duration_label', null, 'source', 'initial_qc') data
from public.initial_qc_inspections r join device_jobs j on j.id=r.job_id
union all
select s.assigned_at occurred_at, 50 sort_order, j.id job_id, jsonb_build_object('id', 'assignment:'||s.id, 'occurred_at', s.assigned_at, 'stage', 'assignment', 'title', initcap(s.department::text)||' assigned to technician', 'actor', coalesce(nullif(s.assigned_technician_name,''),(select nullif(btrim(p.full_name),'') from public.user_profiles p where p.id=s.assigned_technician_id)), 'job_number', j.job_number, 'status', null, 'details', greenloop_private.imei_journey_details(jsonb_build_object('Department', replace(s.department::text,'_',' '), 'Assignment', 'Latest assignment saved on this work step', 'Rework cycle', s.rework_count)), 'parts', '[]'::jsonb, 'cost', null, 'duration_seconds', null, 'duration_label', null, 'source', 'assignment') data
from public.job_work_order_steps s join public.job_work_orders w on w.id=s.work_order_id join device_jobs j on j.id=w.job_id where s.assigned_at is not null
union all
select r.started_at occurred_at, 50 sort_order, j.id job_id, jsonb_build_object('id', 'laboratory-start:'||r.id, 'occurred_at', r.started_at, 'stage', 'laboratory', 'title', 'Laboratory work started', 'actor', (select nullif(btrim(p.full_name),'') from public.user_profiles p where p.id=r.technician_id), 'job_number', j.job_number, 'status', 'in_progress', 'details', greenloop_private.imei_journey_details(jsonb_build_object('Rework cycle', r.rework_cycle)), 'parts', '[]'::jsonb, 'cost', null, 'duration_seconds', null, 'duration_label', null, 'source', 'laboratory') data
from public.laboratory_work_records r join device_jobs j on j.id=r.job_id where r.started_at is not null
union all
select r.completed_at occurred_at, 50 sort_order, j.id job_id, jsonb_build_object('id', 'laboratory-complete:'||r.id, 'occurred_at', r.completed_at, 'stage', 'laboratory', 'title', 'Laboratory work completed', 'actor', (select nullif(btrim(p.full_name),'') from public.user_profiles p where p.id=r.technician_id), 'job_number', j.job_number, 'status', 'completed', 'details', greenloop_private.imei_journey_details(jsonb_build_object('Work done', case when v_names then r.work_done else null end, 'Notes', case when v_names then r.notes else null end, 'Cost basis', 'Recorded material cost', 'Rework cycle', r.rework_cycle)), 'parts', '[]'::jsonb, 'cost', r.material_cost, 'duration_seconds', case when r.active_seconds is not null then r.active_seconds::numeric when r.completed_at>=r.started_at then greatest(0,extract(epoch from r.completed_at-r.started_at)-r.paused_seconds) end, 'duration_label', 'Active repair time', 'source', 'laboratory') data
from public.laboratory_work_records r join device_jobs j on j.id=r.job_id where r.completed_at is not null
union all
select r.started_at occurred_at, 50 sort_order, j.id job_id, jsonb_build_object('id', 'glass-start:'||r.id, 'occurred_at', r.started_at, 'stage', 'glass', 'title', 'Glass work started', 'actor', (select nullif(btrim(p.full_name),'') from public.user_profiles p where p.id=r.assigned_to), 'job_number', j.job_number, 'status', 'in_progress', 'details', greenloop_private.imei_journey_details(jsonb_build_object()), 'parts', '[]'::jsonb, 'cost', null, 'duration_seconds', null, 'duration_label', null, 'source', 'glass') data
from public.glass_work_records r join device_jobs j on j.id=r.job_id where r.started_at is not null
union all
select r.completed_at occurred_at, 50 sort_order, j.id job_id, jsonb_build_object('id', 'glass-complete:'||r.id, 'occurred_at', r.completed_at, 'stage', 'glass', 'title', 'Glass work completed', 'actor', (select nullif(btrim(p.full_name),'') from public.user_profiles p where p.id=r.assigned_to), 'job_number', j.job_number, 'status', 'completed', 'details', greenloop_private.imei_journey_details(jsonb_build_object('Work done', case when v_names then r.work_done else null end, 'Notes', case when v_names then r.notes else null end, 'Cost basis', 'Recorded material cost')), 'parts', '[]'::jsonb, 'cost', r.material_cost, 'duration_seconds', case when r.completed_at>=r.started_at then extract(epoch from r.completed_at-r.started_at) end, 'duration_label', 'Elapsed work time', 'source', 'glass') data
from public.glass_work_records r join device_jobs j on j.id=r.job_id where r.completed_at is not null
union all
select r.reviewed_at occurred_at, 50 sort_order, j.id job_id, jsonb_build_object('id', 'service:'||r.id, 'occurred_at', r.reviewed_at, 'stage', 'laboratory', 'title', 'Service requirement reviewed', 'actor', (select nullif(btrim(p.full_name),'') from public.user_profiles p where p.id=r.reviewed_by), 'job_number', j.job_number, 'status', null, 'details', greenloop_private.imei_journey_details(jsonb_build_object('Service', r.service_name, 'Required', case when r.is_required then 'Yes' else 'No' end, 'Record type', 'Requirement review; not proof of completion', 'Notes', case when v_names then r.notes else null end)), 'parts', '[]'::jsonb, 'cost', null, 'duration_seconds', null, 'duration_label', null, 'source', 'laboratory') data
from public.lab_service_reviews r join device_jobs j on j.id=r.job_id
union all
select r.requested_at occurred_at, 50 sort_order, j.id job_id, jsonb_build_object('id', 'part-request:'||r.id, 'occurred_at', r.requested_at, 'stage', 'parts', 'title', 'Part requested', 'actor', (select nullif(btrim(p.full_name),'') from public.user_profiles p where p.id=r.requested_by), 'job_number', j.job_number, 'status', 'requested', 'details', greenloop_private.imei_journey_details(jsonb_build_object('Request source', replace(r.request_source::text,'_',' '), 'Current request status', r.status, 'Notes', case when v_names then r.notes else null end)), 'parts', jsonb_build_array(jsonb_build_object('name', r.part_name, 'quantity', r.quantity_requested, 'unit_cost', null, 'total_cost', null)), 'cost', null, 'duration_seconds', null, 'duration_label', null, 'source', 'parts') data
from public.job_part_requests r join device_jobs j on j.id=r.job_id
union all
select r.issued_at occurred_at, 50 sort_order, j.id job_id, jsonb_build_object('id', 'part-issue:'||r.id, 'occurred_at', r.issued_at, 'stage', 'parts', 'title', 'Part issued', 'actor', (select nullif(btrim(p.full_name),'') from public.user_profiles p where p.id=r.issued_by), 'job_number', j.job_number, 'status', null, 'details', greenloop_private.imei_journey_details(jsonb_build_object('Cost basis', 'Issued value only; counted in device cost when installed or recorded damaged/faulty', 'Notes', case when v_names then r.issue_notes else null end)), 'parts', jsonb_build_array(jsonb_build_object('name', request.part_name, 'quantity', r.quantity_issued, 'unit_cost', r.unit_cost, 'total_cost', r.quantity_issued*r.unit_cost)), 'cost', null, 'duration_seconds', null, 'duration_label', null, 'source', 'parts') data
from public.part_issue_transactions r join public.job_part_requests request on request.id=r.part_request_id join device_jobs j on j.id=request.job_id
union all
select r.installed_at occurred_at, 50 sort_order, j.id job_id, jsonb_build_object('id', 'part-installation:'||r.id, 'occurred_at', r.installed_at, 'stage', 'parts', 'title', 'Part installed', 'actor', (select nullif(btrim(p.full_name),'') from public.user_profiles p where p.id=r.installed_by), 'job_number', j.job_number, 'status', null, 'details', greenloop_private.imei_journey_details(jsonb_build_object('Notes', case when v_names then r.notes else null end)), 'parts', jsonb_build_array(jsonb_build_object('name', request.part_name, 'quantity', r.quantity_installed, 'unit_cost', r.unit_cost, 'total_cost', r.quantity_installed*r.unit_cost)), 'cost', r.quantity_installed*r.unit_cost, 'duration_seconds', null, 'duration_label', null, 'source', 'parts') data
from public.part_installations r join public.job_part_requests request on request.id=r.part_request_id join device_jobs j on j.id=r.job_id
union all
select r.installed_at occurred_at, 50 sort_order, j.id job_id, jsonb_build_object('id', 'manual-part:'||r.id, 'occurred_at', r.installed_at, 'stage', 'parts', 'title', 'Part installed (manual record)', 'actor', (select nullif(e.event_data->>'technician','') from public.device_events e where e.device_id=r.device_id and e.job_id=r.job_id and e.event_type='laboratory_manual_parts_saved' and e.created_at=r.installed_at order by e.id limit 1), 'job_number', j.job_number, 'status', null, 'details', greenloop_private.imei_journey_details(jsonb_build_object('Recorded by', (select nullif(btrim(p.full_name),'') from public.user_profiles p where p.id=r.installed_by), 'Price', 'Not recorded — excluded from recorded total', 'Notes', case when v_names then r.notes else null end)), 'parts', jsonb_build_array(jsonb_build_object('name', r.part_name, 'quantity', r.quantity, 'unit_cost', null, 'total_cost', null)), 'cost', null, 'duration_seconds', null, 'duration_label', null, 'source', 'parts') data
from public.lab_manual_part_installations r join device_jobs j on j.id=r.job_id
union all
select r.returned_at occurred_at, 50 sort_order, j.id job_id, jsonb_build_object('id', 'part-return:'||r.id, 'occurred_at', r.returned_at, 'stage', 'parts', 'title', case when r.return_condition='restocked' then 'Unused part returned to inventory' else 'Part returned — '||r.return_condition end, 'actor', (select nullif(btrim(p.full_name),'') from public.user_profiles p where p.id=r.returned_by), 'job_number', j.job_number, 'status', null, 'details', greenloop_private.imei_journey_details(jsonb_build_object('Condition', r.return_condition, 'Reason', case when v_names then r.reason else null end, 'Cost basis', case when r.return_condition='restocked' then 'Restocked value; not added to device cost' else 'Consumed part cost recorded once' end)), 'parts', jsonb_build_array(jsonb_build_object('name', r.part_name, 'quantity', r.quantity, 'unit_cost', r.unit_cost, 'total_cost', r.quantity*r.unit_cost)), 'cost', case when r.return_condition in ('damaged','faulty') then r.quantity*r.unit_cost end, 'duration_seconds', null, 'duration_label', null, 'source', 'parts') data
from public.part_return_audit r join device_jobs j on j.id=r.job_id
union all
select r.inspected_at occurred_at, 50 sort_order, j.id job_id, jsonb_build_object('id', 'final-qc:'||r.id, 'occurred_at', r.inspected_at, 'stage', 'final_qc', 'title', case when r.result='pass' then 'Final QC passed' else 'Final QC failed' end, 'actor', (select nullif(btrim(p.full_name),'') from public.user_profiles p where p.id=r.inspected_by), 'job_number', j.job_number, 'status', r.result::text, 'details', greenloop_private.imei_journey_details(jsonb_build_object('Attempt', r.attempt_number, 'Final grade', r.final_grade, 'Final battery health', case when r.final_battery_health is not null then r.final_battery_health::text||'%' end, 'Next step', case when r.routed_to_frame then 'Frame Department' end, 'Failure department', r.failure_department::text, 'Failure reason', case when v_names then r.failure_reason else null end, 'Checks', (select string_agg(c.check_item||': '||case when c.passed then 'Pass' else 'Fail' end,'; ' order by c.created_at,c.id) from public.final_qc_check_results c where c.inspection_id=r.id), 'Notes', case when v_names then r.notes else null end)), 'parts', '[]'::jsonb, 'cost', null, 'duration_seconds', null, 'duration_label', null, 'source', 'final_qc') data
from public.final_qc_inspections r join device_jobs j on j.id=r.job_id
union all
select r.reviewed_at occurred_at, 50 sort_order, j.id job_id, jsonb_build_object('id', 'frame:'||r.id, 'occurred_at', r.reviewed_at, 'stage', 'frame', 'title', 'Frame Department '||case when r.result='pass' then 'passed' else 'failed' end, 'actor', (select nullif(btrim(p.full_name),'') from public.user_profiles p where p.id=r.reviewed_by), 'job_number', j.job_number, 'status', r.result, 'details', greenloop_private.imei_journey_details(jsonb_build_object('Notes', case when v_names then r.notes else null end)), 'parts', '[]'::jsonb, 'cost', null, 'duration_seconds', null, 'duration_label', null, 'source', 'frame') data
from public.frame_department_results r join device_jobs j on j.id=r.job_id
union all
select r.started_at occurred_at, 50 sort_order, j.id job_id, jsonb_build_object('id', 'timer-start:'||r.id, 'occurred_at', r.started_at, 'stage', 'technician', 'title', 'Technician job timer started', 'actor', r.technician_name, 'job_number', j.job_number, 'status', null, 'details', greenloop_private.imei_journey_details(jsonb_build_object('Timing basis', 'Job elapsed time; includes waiting and is separate from active repair time')), 'parts', '[]'::jsonb, 'cost', null, 'duration_seconds', null, 'duration_label', null, 'source', 'technician') data
from public.technician_job_timers r join device_jobs j on j.id=r.job_id
union all
select r.stopped_at occurred_at, 50 sort_order, j.id job_id, jsonb_build_object('id', 'timer-stop:'||r.id, 'occurred_at', r.stopped_at, 'stage', 'technician', 'title', 'Technician job timer stopped', 'actor', r.technician_name, 'job_number', j.job_number, 'status', null, 'details', greenloop_private.imei_journey_details(jsonb_build_object('Stopped by', (select nullif(btrim(p.full_name),'') from public.user_profiles p where p.id=r.stopped_by), 'Timing basis', 'Includes waiting; not added to active repair time')), 'parts', '[]'::jsonb, 'cost', null, 'duration_seconds', coalesce(r.elapsed_seconds,extract(epoch from r.stopped_at-r.started_at)), 'duration_label', 'Technician job elapsed time', 'source', 'technician') data
from public.technician_job_timers r join device_jobs j on j.id=r.job_id where r.stopped_at is not null
union all
select r.scanned_at occurred_at, 50 sort_order, j.id job_id, jsonb_build_object('id', 'export-box:'||r.id, 'occurred_at', r.scanned_at, 'stage', 'export', 'title', 'Scanned into export box', 'actor', (select nullif(btrim(p.full_name),'') from public.user_profiles p where p.id=r.scanned_by), 'job_number', j.job_number, 'status', 'shipped', 'details', greenloop_private.imei_journey_details(jsonb_build_object('Box number', b.box_number, 'Box position', r.serial_no, 'Model in export record', r.model, 'Storage (GB)', r.storage_gb, 'Color in export record', r.color, 'Final grade', r.final_grade, 'Stage meaning', 'Greenloop marks the phone Shipped when scanned into an export box. This is not a courier dispatch timestamp.')), 'parts', '[]'::jsonb, 'cost', null, 'duration_seconds', null, 'duration_label', null, 'source', 'export') data
from public.export_box_items r join public.export_boxes b on b.id=r.box_id join device_jobs j on j.id=r.job_id
union all
select r.dispatched_at occurred_at, 50 sort_order, j.id job_id, jsonb_build_object('id', 'dispatch:'||r.id, 'occurred_at', r.dispatched_at, 'stage', 'export', 'title', 'Stock dispatched', 'actor', (select nullif(btrim(p.full_name),'') from public.user_profiles p where p.id=r.dispatched_by), 'job_number', j.job_number, 'status', null, 'details', greenloop_private.imei_journey_details(jsonb_build_object('Dispatch number', r.stock_out_number, 'Dispatch type', r.stock_out_type::text, 'Destination', case when v_names then r.destination else null end, 'Shipment reference', case when v_names then r.shipment_reference else null end, 'Recipient', case when v_names then r.recipient_name else null end, 'Notes', case when v_names then r.notes else null end)), 'parts', '[]'::jsonb, 'cost', null, 'duration_seconds', null, 'duration_label', null, 'source', 'export') data
from public.stock_out_records r join device_jobs j on j.id=r.job_id
union all
select e.occurred_at occurred_at, 50 sort_order, j.id job_id, jsonb_build_object('id', 'supplier-return:'||e.id, 'occurred_at', e.occurred_at, 'stage', 'stock_return', 'title', case e.action when 'handover' then 'Returned to supplier' when 'requested' then 'Supplier return requested' when 'approve' then 'Supplier return approved' when 'reject' then 'Supplier return rejected' when 'cancel' then 'Supplier return cancelled' when 'settlement' then 'Supplier return settlement recorded' else 'Supplier return — '||replace(e.action,'_',' ') end, 'actor', e.actor_name, 'job_number', j.job_number, 'status', e.to_status, 'details', greenloop_private.imei_journey_details(jsonb_build_object('Return number', r.return_number, 'Supplier code', coalesce(r.source_snapshot->>'supplier_code',s.supplier_code), 'Supplier name', case when v_names then coalesce(r.source_snapshot->>'supplier_name',s.company_name) else null end, 'Reason', r.reason, 'Handover reference', case when e.action='handover' then r.slip_reference end, 'Notes', case when v_names then e.notes else null end)), 'parts', '[]'::jsonb, 'cost', null, 'duration_seconds', null, 'duration_label', null, 'source', 'stock_return') data
from public.supplier_return_events e join public.supplier_returns r on r.id=e.return_id join device_jobs j on j.id=r.job_id left join public.suppliers s on s.id=r.supplier_id where r.device_id=v_device.id and r.archived_at is null
 ), events as (select e.created_at occurred_at, 60 sort_order, e.job_id, jsonb_build_object('id', 'event:'||e.id, 'occurred_at', e.created_at, 'stage', case when e.event_type like '%rework%' then 'rework' when e.event_type='frame_passed_ready_stock' then 'ready_stock' when e.event_type like 'final_qc%' then 'final_qc' when e.event_type like 'frame%' then 'frame' when e.event_type like '%laboratory%' then 'laboratory' when e.event_type like '%glass%' then 'glass' when e.event_type like '%part%' then 'parts' when e.event_type like '%export%' or e.event_type like '%stock_out%' then 'export' else 'workflow' end, 'title', case when v_names then e.event_title when e.event_type='frame_passed_ready_stock' then 'Frame passed and sent to Ready Stock' when e.event_type='ready_stock_rework_started' then 'Ready Stock sent for rework' else initcap(replace(e.event_type,'_',' ')) end, 'actor', (select nullif(btrim(p.full_name),'') from public.user_profiles p where p.id=e.actor_id), 'job_number', j.job_number, 'status', coalesce(e.event_data->>'next_status',e.event_data->>'result',e.event_data->>'status'), 'details', greenloop_private.imei_journey_details(jsonb_build_object('Department', e.event_data->>'department', 'Next department', e.event_data->>'next_department', 'Technician', coalesce(e.event_data->>'technician',e.event_data->>'technician_name',e.event_data->>'assigned_technician_name'), 'Service', e.event_data->>'service', 'Required', e.event_data->>'required', 'Rework cycle', e.event_data->>'rework_cycle', 'Final grade', e.event_data->>'final_grade', 'Final battery health', e.event_data->>'final_battery_health', 'Box number', e.event_data->>'box_number', 'Part', coalesce(e.event_data->>'part_name',e.event_data->>'part'), 'Quantity', e.event_data->>'quantity', 'Reason', case when v_names then coalesce(e.event_data->>'customer_reason',e.event_data->>'reason',e.event_data->>'failure_reason') else null end, 'Notes', case when v_names then e.event_data->>'notes' else null end)), 'parts', '[]'::jsonb, 'cost', null, 'duration_seconds', case when e.event_data->>'active_seconds' ~ '^[0-9]{1,10}$' then (e.event_data->>'active_seconds')::numeric else case when e.event_type='laboratory_completed' then (select extract(epoch from e.created_at-max(r.started_at)) from public.laboratory_work_records r where r.job_id=e.job_id and r.started_at<=e.created_at and (e.event_data->>'step_id' is null or r.work_order_step_id::text=e.event_data->>'step_id')) end end, 'duration_label', case when e.event_data->>'active_seconds' ~ '^[0-9]{1,10}$' then 'Recorded active time' when e.event_type='laboratory_completed' then 'Elapsed laboratory time' end, 'source', 'event') data
from public.device_events e left join device_jobs j on j.id=e.job_id
where e.device_id=v_device.id and (e.job_id is null or j.id is not null)
and not (e.event_type like 'supplier_return_%' and exists(select 1 from public.supplier_return_events se join public.supplier_returns sr on sr.id=se.return_id where sr.device_id=v_device.id and sr.archived_at is null and se.occurred_at=e.created_at))
and not exists(select 1 from structured s where s.job_id=e.job_id and s.occurred_at=e.created_at and split_part(s.data->>'id',':',1)=any(case e.event_type when 'stock_batch_imei_received' then array['entry']::text[]
when 'initial_qc_completed' then array['initial-qc']::text[]
when 'laboratory_work_started' then array['laboratory-start']::text[]
when 'laboratory_work_completed' then array['laboratory-complete']::text[]
when 'glass_work_started' then array['glass-start']::text[]
when 'glass_work_completed' then array['glass-complete']::text[]
when 'part_installed' then array['part-installation']::text[]
when 'laboratory_manual_parts_saved' then array['manual-part']::text[]
when 'laboratory_part_restocked' then array['part-return']::text[]
when 'laboratory_part_damaged' then array['part-return']::text[]
when 'parts_return_approved' then array['part-return']::text[]
when 'final_qc_passed' then array['final-qc']::text[]
when 'final_qc_failed' then array['final-qc']::text[]
when 'frame_failed' then array['frame']::text[]
when 'export_box_scanned' then array['export-box']::text[]
when 'stock_out_completed' then array['dispatch']::text[]
when 'laboratory_service_reviewed' then array['service']::text[] else array[]::text[] end))), all_records as (select * from structured union all select * from events),
 movements as (
 select m.moved_at occurred_at,70 sort_order,m.job_id,jsonb_build_object('id', 'movement:'||m.id, 'occurred_at', m.moved_at, 'stage', 'movement', 'title', 'Location changed', 'actor', (select nullif(btrim(p.full_name),'') from public.user_profiles p where p.id=m.moved_by), 'job_number', j.job_number, 'status', null, 'details', greenloop_private.imei_journey_details(jsonb_build_object('From', case when v_names then fl.location_name else fl.location_code end, 'To', case when v_names then tl.location_name else tl.location_code end, 'Reason', case when v_names then m.movement_reason else null end, 'Notes', case when v_names then m.notes else null end)), 'parts', '[]'::jsonb, 'cost', null, 'duration_seconds', null, 'duration_label', null, 'source', 'movement') data
 from public.device_location_history m left join device_jobs j on j.id=m.job_id left join public.locations fl on fl.id=m.from_location_id left join public.locations tl on tl.id=m.to_location_id
 where m.device_id=v_device.id and (m.job_id is null or j.id is not null)

 ), final_rows as (select * from all_records union all select * from movements)
 select coalesce(jsonb_agg(data order by occurred_at nulls last,sort_order,data->>'id'),'[]'::jsonb) into v_rows from final_rows;

 with device_jobs as (select * from public.jobs where device_id=v_device.id and deleted_at is null), costs as (
 select coalesce((select sum(purchase_cost) from device_jobs),0) purchase,
 coalesce((select sum(p.quantity_installed*p.unit_cost) from public.part_installations p join device_jobs j on j.id=p.job_id),0) installed,
 coalesce((select sum(p.quantity*p.unit_cost) from public.part_return_audit p join device_jobs j on j.id=p.job_id where p.return_condition in ('damaged','faulty')),0) damaged,
 coalesce((select sum(p.material_cost) from public.laboratory_work_records p join device_jobs j on j.id=p.job_id),0) laboratory,
 coalesce((select sum(p.material_cost) from public.glass_work_records p join device_jobs j on j.id=p.job_id),0) glass,
 coalesce((select sum(p.quantity) from public.lab_manual_part_installations p join device_jobs j on j.id=p.job_id),0) manual,
 (select min(coalesce(b.received_at,j.received_at)) from device_jobs j left join public.receiving_batches b on j.receiving_batch_id=b.id) received,
 (select max(e.created_at) from public.device_events e join device_jobs j on j.id=e.job_id where e.device_id=v_device.id and (e.event_type='frame_passed_ready_stock' or (e.event_type='final_qc_passed' and e.event_data->>'next_status' in ('qc_passed','production_pending','production_completed','ready_for_packing','ready_for_shipment') and not exists(select 1 from public.final_qc_inspections f where f.job_id=e.job_id and f.inspected_at=e.created_at and f.routed_to_frame)))) ready
 ) select jsonb_build_object('purchase_cost',purchase,'installed_parts_cost',installed,'damaged_parts_cost',damaged,'laboratory_material_cost',laboratory,'glass_material_cost',glass,'recorded_total_cost',purchase+installed+damaged+laboratory+glass,'unpriced_manual_part_quantity',manual,'first_received_at',received,'last_ready_at',ready,'receipt_to_ready_seconds',case when ready>=received then extract(epoch from ready-received) end,'cost_note','Recorded purchase + installed parts + damaged/faulty parts + laboratory/glass materials. Issued/restocked values are not added again. Manual parts without a recorded price are excluded.') into v_summary from costs;

 select jsonb_build_object('found',true,'version','20261002-imei-history-1','device',jsonb_build_object(
 'device_number',v_device.device_number,'imei_1',v_device.imei_1,'imei_2',v_device.imei_2,'serial_number',v_device.serial_number,'brand',v_device.brand,'model',v_device.model,'storage_gb',v_device.storage_gb,'color',v_device.color,'region',v_device.specification_region,'current_status',v_device.current_status::text,'current_location',(select case when v_names then location_name else location_code end from public.locations where id=v_device.current_location_id),
 'supplier_code',s.supplier_code,'supplier_name',case when v_names then s.company_name end,'customer_code',c.customer_code,'customer_name',case when v_names then c.company_name end),
 'rows',v_rows,'summary',v_summary,'partner_names_visible',v_names) into v_result
 from (select 1) anchor left join lateral (select * from public.jobs where device_id=v_device.id and deleted_at is null order by created_at desc,id limit 1) j on true
 left join public.suppliers s on s.id=j.supplier_id left join public.customers c on c.id=coalesce(j.customer_id,v_device.current_owner_customer_id);
 return v_result;
end;
$journey$;
revoke all on function public.search_imei_journey_v1(text) from public,anon;
grant execute on function public.search_imei_journey_v1(text) to authenticated;

create table if not exists greenloop_private.imei_journey_installation(function_identity text primary key, definition_hash text not null);
revoke all on greenloop_private.imei_journey_installation from public,anon,authenticated;
insert into greenloop_private.imei_journey_installation select p.oid::regprocedure::text,md5(pg_get_functiondef(p.oid)) from pg_proc p where p.oid in ('public.search_imei_journey_v1(text)'::regprocedure,'greenloop_private.imei_journey_details(jsonb)'::regprocedure)
on conflict(function_identity) do update set definition_hash=excluded.definition_hash;
create or replace function public.get_greenloop_imei_history_version()
returns text language sql stable security definer set search_path=pg_catalog,public as $version$
select case when (select count(*) from greenloop_private.imei_journey_installation i where to_regprocedure(i.function_identity) is not null and md5(pg_get_functiondef(to_regprocedure(i.function_identity)))=i.definition_hash)=2
and not has_function_privilege('anon','public.search_imei_journey_v1(text)','EXECUTE')
and has_function_privilege('authenticated','public.search_imei_journey_v1(text)','EXECUTE')
then '20261002-imei-history-1' end;
$version$;
revoke all on function public.get_greenloop_imei_history_version() from public;
grant execute on function public.get_greenloop_imei_history_version() to anon,authenticated;
notify pgrst,'reload schema';
commit;
select public.get_greenloop_imei_history_version() as installed_imei_history_version;
